name: project_SergiBiosca
on:
  push:
    branches:
      - ghActions
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
  cypress-run:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CypressIO
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        id: cypress
        continue-on-error: true
      - run: echo ${{ steps.cypress.outcome }}  > result.txt
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: ./result.txt
  add-badge-job:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ActionArtifact
        uses: actions/download-artifact@v3
        with:
          name: result
      - run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: results
      - uses: ./.github/actions/ReadmeAction
        env:
          resultado: ${{ steps.results.outputs.cypress_outcome }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Sergi Biosca Beneyto"
          author_email: "serbidaw@gmail.com"
          message: "Readme Updated"
          push: true
  deploy-job:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
